### ISSUE TITLE
Follow extends config's `extends`

### ISSUE THREAD

**Issue by alexilyaev** [alexilyaev/stylelint-find-rules#9]
Related to #8 

`stylelint-config-wordpress` has an `extends` of it's own, we should follow `extends` recursively or something.

https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress

**Comment by ntwb** [comment]
The SCSS extends here might make for an interesting test case for this feature:
> https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/blob/master/scss.js#L4-L5

The `scss` config is extending the primary `index.js` in that repo, then also using rules from the stylelint plugin `stylelint-scss`

----

I should probably update this SCSS config to _extend_ `stylelint-config-recommended-scss` rather than call the rules directly in the `stylelint-config-wordpress/scss` config 🤔 
> https://github.com/kristerkari/stylelint-config-recommended-scss/blob/master/index.js

**Comment by alexilyaev** [comment]
Landed in v2.0.0:  
https://github.com/alexilyaev/stylelint-find-rules/releases/tag/v2.0.0
